name: polkadot-metrcis

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
    environment:
      CONFIG_PATH: config/config.yaml
    command: ["node", "src/app.js", "${CONFIG_PATH}"]
