{
 "title": "Polkadot",
 "time": { "from": "now-4m", "to": "now" },
 "templating": {
  "list": [
   { "name": "chain", "label": "Chain Name", "query": { "query": "query_result(chain_info)" } },
   { "name": "Era", "query": "activeEra,currentEra\n" }
  ]
 },
 "panels": [
  { "title": "Sessions, Era. and Block", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Session",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "session_current_index{chain=\"$chain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Number",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "current_block_number{chain=\"$chain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Era",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{__name__=~\"$Era\", chain=\"$chain\", param=~\"index|^$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Validator",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "count by (chain, era) (erasRewardPoints{chain=\"$chain\", era=\"$Era\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Rewards in $Era", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$Era",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (validator) (erasRewardPoints{chain=\"$chain\",era=\"$Era\"})",
     "legendFormat": "{{validator}}"
    }
   ]
  }
 ]
}