global:
  resolve_timeout: 5m
  slack_api_url: "SLACK_API_URL"

route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 5m
  receiver: "default"
  routes:
    - receiver: "slack_critical"
      matchers:
        - severity="critical"

    - receiver: "slack_warning"
      matchers:
        - severity="warning"

    - receiver: "slack_info"
      matchers:
        - severity="info"

receivers:
  - name: "slack_critical"
    slack_configs:
      - channel: "#SLACK_CHANNEL_NAME"
        send_resolved: true
        icon_emoji: ":rotating_light:"
        title: "🚨 *Critical Alert: {{ .CommonAnnotations.summary }}* 🚨"
        text: |
          *Description:* {{ .CommonAnnotations.description }}
          {{ range .Alerts }}
          - *Chain:* {{ .Labels.chain }}
          - *Validator:* {{ .Labels.validator }}
          - *Value:* {{ .Annotations.description }}
          {{ end }}

  - name: "slack_warning"
    slack_configs:
      - channel: "#SLACK_CHANNEL_NAME"
        send_resolved: true
        icon_emoji: ":warning:"
        title: "⚠️ *Warning: {{ .CommonAnnotations.summary }}*"
        text: |
          *Description:* {{ .CommonAnnotations.description }}
          {{ range .Alerts }}
          - *Chain:* {{ .Labels.chain }}
          - *Validator:* {{ .Labels.validator }}
          - *Value:* {{ .Annotations.description }}
          {{ end }}

  - name: "slack_info"
    slack_configs:
      - channel: "#SLACK_CHANNEL_NAME"
        send_resolved: true
        icon_emoji: ":information_source:"
        title: "ℹ️ *Info: {{ .CommonAnnotations.summary }}*"
        text: |
          *Description:* {{ .CommonAnnotations.description }}
          {{ range .Alerts }}
          - *Chain:* {{ .Labels.chain }}
          - *Session:* {{ .Labels.session_current_index }}
          - *Era:* {{ .Labels.era }}
          {{ end }}

  - name: "default"
    slack_configs:
      - channel: "#SLACK_CHANNEL_NAME"
        send_resolved: true
        icon_emoji: ":robot_face:"
        title: "🚀 *Unhandled Alert: {{ .CommonAnnotations.summary }}*"
        text: |
          *Description:* {{ .CommonAnnotations.description }}
          {{ range .Alerts }}
          - *Chain:* {{ .Labels.chain }}
          - *Details:* {{ .Annotations.description }}
          {{ end }}
