server:
  port: 8080

blockchain:
  rpc_url: "wss://rpc.polkadot.io"

metrics_backend:
  type: "prometheus"  # Options: "prometheus", "influxdb", "none"
  influxdb:
    url: "http://localhost:8086"
    token: "your-influxdb-token"
    org: "your-org"
    bucket: "your-bucket"

metrics:
  - pallet: "session"
    storage_items:
      - name: "currentIndex"
      # - name: "validators"
  - pallet: "system"
    storage_items:
      - name: "number"
  - pallet: "staking"
    storage_items:
      - name: "activeEra"
      - name: "erasRewardPoints"
        params: ["activeEra"]
      - name: "currentEra"
      - name: "erasRewardPoints"
        params: ["currentEra"]
      - name: "erasTotalStake"
        params: [1699]
  #     - name: "claimedRewards"
  #       params: [1699, "1BwjS7oyQ5EDGrdfMBgbVRAXkW5fnbWeQAYWaSCzu27dwwh"]
  # - pallet: "paraSessionInfo"
  #   storage_items:
  #     - name: "accountKeys"
  #       params: [10458]   # Providing a specific param value
  #     - name: "palletVersion"
  #     - name: "sessions"
  #       params: [10456]
  # - pallet: "historical"
  #   storage_items:
  #     - name: "storedRange"
  # - pallet: "balances"
  #   storage_items:
  #     - name: "account"
  #       params: ["1BwjS7oyQ5EDGrdfMBgbVRAXkW5fnbWeQAYWaSCzu27dwwh"]
  # - pallet: "bounties"
  #   storage_items:
  #     - name: "bounties"
  #       params: [64]

param_resolvers:
  staking:
    activeEra: "unwrapOrDefault().index.toNumber()"
    currentEra: "unwrapOrDefault().toNumber()"

logging:
  level: "debug"  # Options: "debug", "info", "warn", "error"
  log_to_file: false
  log_file: "logs/app.log"
  error_log_file: "logs/error.log"
