server:
  port: 8080

blockchain:
  rpc_url: "wss://rpc.polkadot.io"

metrics_backend:
  type: "none"  # Options: "prometheus", "influxdb", "none"
  influxdb:
    url: "http://localhost:8086"
    token: "your-influxdb-token"
    org: "your-org"
    bucket: "your-bucket"

metrics:
  - pallet: "session"
    storage_items:
      - name: "currentIndex"
      # - name: "validators"
  - pallet: "system"
    storage_items:
      - name: "number"
      # - name: "parentHash"
  - pallet: "staking"
    storage_items:
      - name: "activeEra"
      - name: "currentEra"
      # - name: "erasRewardPoints"
      #   params: ["activeEra"]
      # - name: "erasRewardPoints"
      #   params: ["currentEra"]

logging:
  level: "info"  # Options: "debug", "info", "warn", "error"
  log_to_file: false
  log_file: "logs/app.log"
  error_log_file: "logs/error.log"
