server:
  port: 8080

blockchain:
  rpc_url: "wss://rpc.polkadot.io"

metrics_backend:
  type: "none"  # Options: "prometheus", "influxdb", "none"
  influxdb:
    url: "http://localhost:8086"
    token: "your-influxdb-token"
    org: "your-org"
    bucket: "your-bucket"

metrics:
  - name: "active_era"
    pallet: "staking"
    storage_item: "activeEra"
  - name: "current_era"
    pallet: "staking"
    storage_item: "currentEra"
  - name: "eras_reward_points_active"
    pallet: "staking"
    storage_item: "erasRewardPoints"
    params: ["activeEra"]
  - name: "eras_reward_points_current"
    pallet: "staking"
    storage_item: "erasRewardPoints"
    params: ["currentEra"]
  - name: "session_index"
    pallet: "session"
    storage_item: "currentIndex"

logging:
  level: "debug"  # Options: "debug", "info", "warn", "error"
  log_to_file: false
  log_file: "logs/app.log"
  error_log_file: "logs/error.log"
