server:
  port: 8080

blockchain:
  rpc_urls:
    - url: "wss://rpc.polkadot.io"
      priority: 1
    - url: "wss://polkadot-rpc.dwellir.com"
      priority: 2
    - url: "wss://polkadot.api.onfinality.io/public-ws"
      priority: 3
  health_check_interval: 30  # seconds
  switch_threshold: 3        # number of failed requests before switching
  reconnect_interval: 5      # seconds

metrics_backend:
  type: "prometheus"  # Options: "prometheus", "influxdb", "none"
  influxdb:
    url: "http://localhost:8086"
    token: "your-influxdb-token"
    org: "your-org"
    bucket: "your-bucket"

metrics:
  - pallet: "session"
    storage_items:
      - name: "currentIndex"
      # - name: "validators"
  - pallet: "system"
    storage_items:
      - name: "number"
  - pallet: "staking"
    storage_items:
      - name: "activeEra"
    #   - name: "erasRewardPoints"
    #     params: ["activeEra"]
    #   - name: "currentEra"
    #   - name: "erasRewardPoints"
    #     params: ["currentEra"]
      - name: "erasTotalStake"
        params: [1752]
      - name: "claimedRewards"
        params: [1751]  # Query all claimed rewards for era 1752

param_resolvers:
  staking:
    activeEra: "unwrapOrDefault().index.toNumber()"
    currentEra: "unwrapOrDefault().toNumber()"

logging:
  level: "debug"  # Options: "debug", "info", "warn", "error"
  log_to_file: false
  log_file: "logs/app.log"
  error_log_file: "logs/error.log"
