groups:
  - name: BlockchainAlerts
    rules:
      - alert: SessionChange
        expr: |
          changes(session_current_index[5m]) > 0
        for: 1m
        labels:
          severity: info
        annotations:
          summary: "New Session Detected"
          description: "A new session has started on chain {{ $labels.chain }}. Current session index: {{ $value }}."

      - alert: EraChange
        expr: |
          changes(activeEra[5m]) > 0 or changes(currentEra[5m]) > 0
        for: 1m
        labels:
          severity: info
        annotations:
          summary: "Era Change Detected"
          description: "The activeEra or currentEra has changed on chain {{ $labels.chain }}."

      - alert: BlockNumberNotChanging
        expr: |
          delta(current_block_number[1m]) == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Blockchain Stalled"
          description: "The block number on chain {{ $labels.chain }} has not changed in the last 5 minutes. Possible issue with block production."

  - name: ValidatorRewardsAlerts
    rules:
      - alert: LowValidatorRewards
        expr: |
          sum by (chain, era, validator) (
            erasRewardPoints * on (era) group_left () (activeEra or currentEra)
          ) < 16000
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Low rewards for validators"
          description: "Validator {{ $labels.validator }} on chain {{ $labels.chain }} has low rewards in era {{ $labels.era }}. Current reward points: {{ $value }}"
