# This file is not intended to be modified - any changes here could be overwritten next time you update.
# If you just need to add some new scrape targets to Prometheus, place these in the conf.d folder.
# You can use the existing files as inspiration, and the docs are here:
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
#
# If you need to override the settings in this file, or add other top-level configuration
# (e.g.) remote_write config, please use custom-prom.yml.
# The modifications in that file will supercede the settings here (or extend, in the case of lists)

global:
  scrape_interval:     10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout:      10s # Timeout must be shorter than the interval

# Service detection from the Docker socket.
#
# If you have extra containers you'd like to monitor, you will need to add the following labels:
#   - `metrics.scrape=true`
#   - `metrics.port=<the metrics port>`
# And you will have to ensure that the container is connected to the same network by including
# `ext-network.yml` in your .env file.

scrape_configs:
  - job_name: 'polkadot-metrics-exporter'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - 'polkadot-metrics-exporter:8080'

rule_files:
  - '/etc/prometheus/alert_rules.yaml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
